### ISSUE TITLE
k4os and MySql.data.dll

### ISSUE THREAD

**Issue by RoBoT245** [d3adwolf/libraries-unturned#1]
**Describe the bug**
Plugins are unable to find the k4os.Compression.LZ4.dll and the MySql.data.dll files (They are in the libraries folder)

**To Reproduce**
1. reinstall libraries using the ones provided here
2. launch the server
3. error from any plugin that needs 1 of those 2 files

**Expected behavior**
For there to be no error message and for it to work.

**Screenshots**

**Desktop (please complete the following information):**
Linux, Modern Hosting server

**Comment by RoBoT245** [comment]
![brave_bKi1j9b9Qq](https://user-images.githubusercontent.com/109394847/189451687-655b9adb-a6df-4276-a6c7-56f3fb3c1d9e.png)

**Comment by RoBoT245** [comment]
Fixed the issue, just had to download an older version of k4os and a different version of MySQL.data

**Comment by d3adwolf** [comment]
Got it, okay, can you make a pull request for new .dlls?
